In [1]:
import numpy as np

In [3]:
v_cut = 4.8
n_v = 6
v_mesh = np.array([-v_cut + (2 * v_cut / n_v) * (i + 0.5) for i in range(n_v)])
borders = np.array([-v_cut + (2 * v_cut / n_v) * (i) for i in range(n_v + 1)])
print(v_mesh)
print(borders)

[-4.  -2.4 -0.8  0.8  2.4  4. ]
[-4.8 -3.2 -1.6  0.   1.6  3.2  4.8]


In [8]:
v_x = -2.4
(v_x + v_cut) / (2 * v_cut) * n_v + 0.5

2.0

In [21]:
v_x = -3.1
v_mesh[int(np.floor(n_v / 2 * (1 + v_x / v_cut)))]

-2.4

In [16]:
v_sq = v_mesh ** 2 * np.ones(n_v).reshape(-1, 1) + np.ones(n_v) * (v_mesh ** 2).reshape(-1, 1)
v_sq = v_sq * [v_sq <= 4.8**2]
v_sq


array([[[ 0.  , 21.76, 16.64, 16.64, 21.76,  0.  ],
        [21.76, 11.52,  6.4 ,  6.4 , 11.52, 21.76],
        [16.64,  6.4 ,  1.28,  1.28,  6.4 , 16.64],
        [16.64,  6.4 ,  1.28,  1.28,  6.4 , 16.64],
        [21.76, 11.52,  6.4 ,  6.4 , 11.52, 21.76],
        [ 0.  , 21.76, 16.64, 16.64, 21.76,  0.  ]]])

In [17]:
distr = np.exp(-0.5 * v_sq)
print(np.array_str(distr, precision=3))

[[[1.000e+00 1.883e-05 2.436e-04 2.436e-04 1.883e-05 1.000e+00]
  [1.883e-05 3.151e-03 4.076e-02 4.076e-02 3.151e-03 1.883e-05]
  [2.436e-04 4.076e-02 5.273e-01 5.273e-01 4.076e-02 2.436e-04]
  [2.436e-04 4.076e-02 5.273e-01 5.273e-01 4.076e-02 2.436e-04]
  [1.883e-05 3.151e-03 4.076e-02 4.076e-02 3.151e-03 1.883e-05]
  [1.000e+00 1.883e-05 2.436e-04 2.436e-04 1.883e-05 1.000e+00]]]
